name: Test PC Skeletor code

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: 'Test PC Skeletor'
        run: |
          cd pc_skeletor
          python test.py
          ls -la 
          ls -la data
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        run: |
          echo "This folder is upload:" && ls ${{ github.workspace }}/data
        with:
          name: skeleton-artifact
          path: ${{ github.workspace }}/data/**/*
          retention-days: 5